name: Release
on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - 'images/*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          architecture: 'x64'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: make bundle
      - run: make installer

      - name: Upload installer
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows-installer
          path: dist/installer/*.exe

      - name: Upload zip
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows-portable
          path: dist/Stagehand

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          architecture: 'x64'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: make bundle

      - name: Upload zip
        uses: actions/upload-artifact@v3.1.0
        with:
          name: linux-portable
          path: dist/Stagehand
